In [1]:
import torch

In [2]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
x.numel()

12

In [4]:
x.shape

torch.Size([12])

In [5]:
x = x.reshape(3,4) # 3 e 4 são o numero de linhas e colunas
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [6]:
x[2,2] # aqui, os numeros são os índices de cada elemento do tensor nas linhas e colunas, começando do 0.

tensor(10.)

In [7]:
#For a given a tensor of size n and target shape (h,w), we know that w=n/h. 
#To automatically infer one component of the shape, we can place a -1 for the shape component that should be inferred automatically.
#In our case, instead of calling x.reshape(3, 4), we could have equivalently called x.reshape(-1, 4) or x.reshape(3, -1).
x = x.reshape(1,-1)
x

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]])

In [8]:
x = x.reshape(-1,4)
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
torch.randn(2,3,4) #The following snippet creates a tensor with elements drawn from a standard Gaussian (normal) distribution
                   #with mean 0 and standard deviation 1.

tensor([[[ 1.4670, -0.1311,  1.2903, -0.4955],
         [ 0.6747,  0.2308, -1.7486,  0.3429],
         [-0.3970, -0.3124,  0.1325, -2.2894]],

        [[-0.4150, -0.8096,  0.8144,  1.2962],
         [ 0.2877, -2.6183, -0.7909,  0.2676],
         [-1.7453,  1.3470,  1.6039,  0.6788]]])

In [12]:
#Finally, we can construct tensors by supplying the exact values for each element by supplying (possibly nested) Python list(s) containing
#numerical literals.
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [13]:
#o primeiro par de colchetes deve englobar todas as n dimensões (o tensor como um todo), o segundo par a matriz (2D), e os seguintes pares
#cada linha da matriz. Após a vírgula, repita a partir do segundo par.
y = torch.tensor([[[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]] , [[8, 9, 6, 4], [5, 7, 2, 0], [9, 9, 4, 6]]])
y

tensor([[[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]],

        [[8, 9, 6, 4],
         [5, 7, 2, 0],
         [9, 9, 4, 6]]])

In [14]:
x[-1], x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [15]:
y[0,-1], y[-1], y[-1,0:2], y[-1,-1,-1]

(tensor([4, 3, 2, 1]),
 tensor([[8, 9, 6, 4],
         [5, 7, 2, 0],
         [9, 9, 4, 6]]),
 tensor([[8, 9, 6, 4],
         [5, 7, 2, 0]]),
 tensor(6))

In [16]:
y[-1, 0, 2] = 87
y

tensor([[[ 2,  1,  4,  3],
         [ 1,  2,  3,  4],
         [ 4,  3,  2,  1]],

        [[ 8,  9, 87,  4],
         [ 5,  7,  2,  0],
         [ 9,  9,  4,  6]]])

In [17]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [18]:
x[1:] #começa da linha de índice 1 vai até o fim

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [19]:
x[:2] #começa do começo e vai até a linha de indice 2 (não inclusa)

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [20]:
x[:2, 3] #após a vírgula, o número corresponde à coluna

tensor([3., 7.])

In [21]:
x[:2, 1:3] #do começo até a linha de indice 2 (não inclusa), e coluna de índice 1 até coluna de índice 3 (não inclusa)

tensor([[1., 2.],
        [5., 6.]])

In [22]:
x[:2, :] #do começo até a linha de indice 2 (não inclusa), todas as colunas. O mesmo que apenas x[:2]

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [23]:
x[:2] = 12 # o mesmo que x[:2, :] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [24]:
y

tensor([[[ 2,  1,  4,  3],
         [ 1,  2,  3,  4],
         [ 4,  3,  2,  1]],

        [[ 8,  9, 87,  4],
         [ 5,  7,  2,  0],
         [ 9,  9,  4,  6]]])

In [25]:
y[0, 1:3, 3:] = 63
y

tensor([[[ 2,  1,  4,  3],
         [ 1,  2,  3, 63],
         [ 4,  3,  2, 63]],

        [[ 8,  9, 87,  4],
         [ 5,  7,  2,  0],
         [ 9,  9,  4,  6]]])

In [26]:
torch.exp(x)

tensor([[162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [  2980.9580,   8103.0840,  22026.4648,  59874.1406]])

In [27]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [28]:
X = torch.arange(12, dtype=torch.float32).reshape((3,-1))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [29]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [30]:
x

tensor([1., 2., 4., 8.])

In [31]:
x.sum()

tensor(15.)

In [32]:
a = torch.tensor([1, 2, 4, 8]).reshape(4, 1)
b = torch.arange(3).reshape((1, 3))
a, b

(tensor([[1],
         [2],
         [4],
         [8]]),
 tensor([[0, 1, 2]]))

In [33]:
a + b

tensor([[ 1,  2,  3],
        [ 2,  3,  4],
        [ 4,  5,  6],
        [ 8,  9, 10]])

In [34]:
id(Y)

2626714499248

In [35]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [36]:
a

tensor([[1],
        [2],
        [4],
        [8]])

In [37]:
b

tensor([[0, 1, 2]])

In [38]:
Z = torch.zeros_like(a+b) # o termo entre parenteses deve ter o formato que Z assumirá após receber os valores definitivos
Z

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [39]:
Z = torch.zeros_like(X) # neste caso, X e Y têm o mesmo formato, então basta apenas colocar X (ou Y) dentro do parênteses. apenas a ou b não serviria,
                        #pois um deles é (4, 1), e o outro (1,3). Deveria usar a soma, como na célula acima, cujo formato é (4,3)
Z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
print('id(Z):', id(Z))

id(Z): 2626707978576


In [41]:
Z[:] = X + Y  #fazendo assim , o resultado e X + Y é atribuído à variável Z com mesmo endereço que a anterior, pois você simplesmente
              # substituiu os zeros com os números atuais. Não usar o [:] faz com que Z seja alocada a um novo espaço na memória (usa mais memória).

In [42]:
Z

tensor([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]])

In [43]:
print('id(Z):', id(Z))

id(Z): 2626707978576


In [44]:
#X += Y também cumpre o mesmo objetivo de preservar a ID.
before = id(X)
X += Y
id(X) == before

True

In [45]:
X

tensor([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]])

In [46]:
#Converting to a NumPy tensor (ndarray), or vice versa, is easy. The torch tensor and NumPy array will share their underlying memory, 
#and changing one through an in-place operation will also change the other.
A = X.numpy()
A

array([[ 2.,  3.,  8.,  9.],
       [ 9., 12., 15., 18.],
       [20., 21., 22., 23.]], dtype=float32)

In [47]:
B = torch.from_numpy(A)
B

tensor([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]])

In [48]:
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [49]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a) #converter um tensor de um único elemento a um escalar python

(tensor([3.5000]), 3.5, 3.5, 3)

In [50]:
X

tensor([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]])

In [51]:
Y

tensor([[ 2.,  2.,  6.,  6.],
        [ 5.,  7.,  9., 11.],
        [12., 12., 12., 12.]])

In [52]:
X > Y

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [53]:
X = torch.arange(8).reshape(4, 2, 1)
Y = torch.arange(32).reshape(4, 2 ,4)

print(f"{X}, \n\n\n{Y}, \n\n\n{X + Y}")

tensor([[[0],
         [1]],

        [[2],
         [3]],

        [[4],
         [5]],

        [[6],
         [7]]]), 


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31]]]), 


tensor([[[ 0,  1,  2,  3],
         [ 5,  6,  7,  8]],

        [[10, 11, 12, 13],
         [15, 16, 17, 18]],

        [[20, 21, 22, 23],
         [25, 26, 27, 28]],

        [[30, 31, 32, 33],
         [35, 36, 37, 38]]])


In [54]:
X = torch.arange(8).reshape(4, 2, 1)
Y = torch.arange(8).reshape(1, 1 ,8)

print(f"{X}, \n\n\n{Y}, \n\n\n{X + Y}")

tensor([[[0],
         [1]],

        [[2],
         [3]],

        [[4],
         [5]],

        [[6],
         [7]]]), 


tensor([[[0, 1, 2, 3, 4, 5, 6, 7]]]), 


tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7],
         [ 1,  2,  3,  4,  5,  6,  7,  8]],

        [[ 2,  3,  4,  5,  6,  7,  8,  9],
         [ 3,  4,  5,  6,  7,  8,  9, 10]],

        [[ 4,  5,  6,  7,  8,  9, 10, 11],
         [ 5,  6,  7,  8,  9, 10, 11, 12]],

        [[ 6,  7,  8,  9, 10, 11, 12, 13],
         [ 7,  8,  9, 10, 11, 12, 13, 14]]])


In [55]:
X = torch.arange(8).reshape(4, 2, 1)
Y = torch.arange(8).reshape(1, 2 ,4)

print(f"{X}, \n\n\n{Y}, \n\n\n{X + Y}")

tensor([[[0],
         [1]],

        [[2],
         [3]],

        [[4],
         [5]],

        [[6],
         [7]]]), 


tensor([[[0, 1, 2, 3],
         [4, 5, 6, 7]]]), 


tensor([[[ 0,  1,  2,  3],
         [ 5,  6,  7,  8]],

        [[ 2,  3,  4,  5],
         [ 7,  8,  9, 10]],

        [[ 4,  5,  6,  7],
         [ 9, 10, 11, 12]],

        [[ 6,  7,  8,  9],
         [11, 12, 13, 14]]])
