In [1]:
import torch
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x+y, x*y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [2]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [3]:
x[2]

tensor(2)

In [4]:
x = torch.tensor([[[3.0,2.0,3.0],[5.0,4.0,5.0]],[[6.0,7.0,6.0],[8.0,9.0,8.0]],[[3.0,2.0,3.0],[5.0,4.0,5.0]],[[6.0,7.0,6.0],[8.0,9.0,8.0]]]) #tensor 3D
x

tensor([[[3., 2., 3.],
         [5., 4., 5.]],

        [[6., 7., 6.],
         [8., 9., 8.]],

        [[3., 2., 3.],
         [5., 4., 5.]],

        [[6., 7., 6.],
         [8., 9., 8.]]])

In [5]:
#o tensor é composto por matrizes.
print(len(x)) #comprimento da dimensão
print(x.shape) #4 -> quatro matrizes que compoem o tensor(dimensao0)
               #2 -> duas linhas em cada matriz(dimensao1)
               #3 -> três colunas em cada(dimensao2)

#o número de elementos em torch.Size([]) define se o vetor é 1D, 2D, 3D, 4D, etc...
#x.shape retorna torch.Size([dimensão0, dimensão1, dimensão2, dimensão3,..., etc.]). Num tensor 3D, a dimensão 0 seria a quantidade de matrizes 2D. 
#Um tensor 2D é uma matriz, e a dimensão 0 será o número de linhas desta matriz. Um tensor 1D é um vetor, e a dimensão 0 será o número de elementos. 
#Num tensor 4D, dimensão 0 seria a quantidade de matrizes 3D que o compõem.
# a visualização de cubos não funciona muito bem para tensores. é melhor visualizar cada matriz 2D que compõe um tensor 3D
#como uma camada (2D) numa pilha de camadas
#len() retorna o comprimento da dimensão0

4
torch.Size([4, 2, 3])


In [6]:
x = torch.tensor([[3.0,2.0,3.0],[5.0,4.0,5.0]]) #tensor 2D
x

tensor([[3., 2., 3.],
        [5., 4., 5.]])

In [7]:
print(len(x)) #como há apenas uma matriz (tensor 2D), ao inves de retornar o numero de matrizes no tensor, retorna o número de linhas no tensor
print(x.shape) #só há um vetor no tensor(tensor 2D), e a dimensao0 é o número de linhas presente no tensor.

2
torch.Size([2, 3])


In [8]:
x = torch.tensor([3.0,2.0,3.0]) #tensor 1D
x

tensor([3., 2., 3.])

In [9]:
print(len(x))
print(x.shape)

3
torch.Size([3])


In [10]:
tensor_4d = torch.tensor([
    [  # Primeiro "bloco" da Dimensão 0
        [  # Primeira "matriz" da Dimensão 1
            [1.0, 2.0],  # Primeira "linha" da Dimensão 2
            [3.0, 4.0]   # Segunda "linha" da Dimensão 2
        ],
        [  # Segunda "matriz" da Dimensão 1
            [5.0, 6.0],
            [7.0, 8.0]
        ]
    ],
    [  # Segundo "bloco" da Dimensão 0
        [  # Primeira "matriz" da Dimensão 1
            [9.0, 10.0],
            [11.0, 12.0]
        ],
        [  # Segunda "matriz" da Dimensão 1
            [13.0, 14.0],
            [15.0, 16.0]
        ]
    ]
])

print(tensor_4d)
print(tensor_4d.shape)

tensor([[[[ 1.,  2.],
          [ 3.,  4.]],

         [[ 5.,  6.],
          [ 7.,  8.]]],


        [[[ 9., 10.],
          [11., 12.]],

         [[13., 14.],
          [15., 16.]]]])
torch.Size([2, 2, 2, 2])


In [11]:
A = torch.arange(6) #tensor 1D (vetor)
A

tensor([0, 1, 2, 3, 4, 5])

In [12]:
A = A.reshape(3,2) #transformou tensor 1D (vetor) em tensor 2D (matriz)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [13]:
A.T #transpõe a matriz (linhas viram colunas e vice-versa)

tensor([[0, 2, 4],
        [1, 3, 5]])

In [14]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]]) #Matrizes quadradas que são iguais às suas transpostas são matrizes simetricas
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [15]:
torch.arange(24).reshape(3, 2, 4) #transformou tensor 1D em tensor 3D. Esse tensor 3D poderia representar uma imagem de 2px de altura e 4px de largura, e 
                                  #com 3 canais, um para vermelho(R), outro para verde(G), e outro para azul (B). Cada número está na
                                  #localização de um pixel, e seu valor representa o valor (intensidade) do canal.

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [16]:
torch.arange(24).reshape(2, 3, 2, 2) #transformou tensor 1D em tensor 4D. #este tensor 4D poderia representar uma coleção de duas imagens,
                                     #cada uma delas com dimensão 2x2 px e 3 canais de cor.

tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11]]],


        [[[12, 13],
          [14, 15]],

         [[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]]])

In [17]:
#Scalars, vectors, matrices, and higher-order tensors all have some handy properties. For example, elementwise operations produce
#outputs that have the same shape as their operands.

A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [18]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [19]:
#Adding or multiplying a scalar and a tensor produces a result with the same shape as the original tensor.
a = 2
X = torch.arange(24).reshape(2, 3, 4)
X, a + X, (a*X), (a * X).shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]),
 torch.Size([2, 3, 4]))

In [20]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum() #x.sum()calcula a soma dos elementos do vetor (tensor 1D)

(tensor([0., 1., 2.]), tensor(3.))

In [21]:
A, A.shape, A.sum() #no caso de tensores de dimensões arbitrárias, .sum() soma normalmente elemento por elemento em cada coluna/linha, retorna escalar

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]),
 tensor(15.))

In [22]:
x = torch.tensor([[[3.0,2.0,3.0],[5.0,4.0,5.0]],[[6.0,7.0,6.0],[8.0,9.0,8.0]],[[3.0,2.0,3.0],[5.0,4.0,5.0]],[[6.0,7.0,6.0],[8.0,9.0,8.0]]])
x, x.shape, x.sum() # novamente, soma-se elemento por elemento, chegando no resultado final de 132 e retorna escalar

(tensor([[[3., 2., 3.],
          [5., 4., 5.]],
 
         [[6., 7., 6.],
          [8., 9., 8.]],
 
         [[3., 2., 3.],
          [5., 4., 5.]],
 
         [[6., 7., 6.],
          [8., 9., 8.]]]),
 torch.Size([4, 2, 3]),
 tensor(132.))

In [23]:
A, A.shape, A.sum(axis=0), A.sum(axis=0).shape #especificar o axis=0 faz com que as some-se apenas ao longo do eixo 0 (dimensão 0),
                                               #que, neste caso (tensor 2D), engloba as duas linhas. Então soma-se um elemento de cada linha.
                                               #0+3, 1+4, 2+5

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]),
 tensor([3., 5., 7.]),
 torch.Size([3]))

In [24]:
x, x.shape, x.sum(axis=0), x.sum(axis=0).shape #soma-se ao longo do eixo 0 (dimensão 0). Neste caso (tensor 3D), a dimensão 0
                                               #engloba cada uma das matrizes 2D, então soma-se um elemento de cada matriz:
                                               #Posição [0, 0] do resultado: 3.0 + 6.0 + 3.0 + 6.0 = 18.0
                                               #Posição [0, 1] do resultado: 2.0 + 7.0 + 2.0 + 7.0 = 18.0
                                               #Posição [0, 2] do resultado: 3.0 + 6.0 + 3.0 + 6.0 = 18.0
                                               #Posição [1, 0] do resultado: 5.0 + 8.0 + 5.0 + 8.0 = 26.0
                                               #Posição [1, 1] do resultado: 4.0 + 9.0 + 4.0 + 9.0 = 26.0
                                               #Posição [1, 2] do resultado: 5.0 + 8.0 + 5.0 + 8.0 = 26.0

(tensor([[[3., 2., 3.],
          [5., 4., 5.]],
 
         [[6., 7., 6.],
          [8., 9., 8.]],
 
         [[3., 2., 3.],
          [5., 4., 5.]],
 
         [[6., 7., 6.],
          [8., 9., 8.]]]),
 torch.Size([4, 2, 3]),
 tensor([[18., 18., 18.],
         [26., 26., 26.]]),
 torch.Size([2, 3]))

In [25]:
x = torch.arange(24).reshape(2, 3, 2, 2)
x, x.shape, x.sum(axis=0), x.sum(axis=0).shape #neste caso (tensor 4D), a dimensão 0 engloba as "coleções", então soma-se um elemento de cada "coleção"
                                               #0+12, 1+13, 2+14, 3+15, 4+16....etc.

(tensor([[[[ 0,  1],
           [ 2,  3]],
 
          [[ 4,  5],
           [ 6,  7]],
 
          [[ 8,  9],
           [10, 11]]],
 
 
         [[[12, 13],
           [14, 15]],
 
          [[16, 17],
           [18, 19]],
 
          [[20, 21],
           [22, 23]]]]),
 torch.Size([2, 3, 2, 2]),
 tensor([[[12, 14],
          [16, 18]],
 
         [[20, 22],
          [24, 26]],
 
         [[28, 30],
          [32, 34]]]),
 torch.Size([3, 2, 2]))

In [26]:
A, A.shape, A.sum(axis=1), A.sum(axis=1).shape #especificar o axis=1 faz com que as some-se apenas ao longo do eixo 1 (dimensão 1),
                                               #que, neste caso (tensor 2D), engloba as três colunas. Então soma-se um elemento de cada coluna.
                                               #0+1+2, 3+4+5

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]),
 tensor([ 3., 12.]),
 torch.Size([2]))

In [27]:
x = torch.tensor([[[3.0,2.0,3.0],[5.0,4.0,5.0]],[[6.0,7.0,6.0],[8.0,9.0,8.0]],[[3.0,2.0,3.0],[5.0,4.0,5.0]],[[6.0,7.0,6.0],[8.0,9.0,8.0]]])
x, x.shape, x.sum(axis=1), x.sum(axis=1).shape #soma-se ao longo do eixo 1 (dimensão 1). Neste caso (tensor 3D), a dimensão 1
                                               #engloba as linhas das matrizes 2D, então soma-se um elemento de cada linha:
                                               #Posição [0, 0] do resultado: 3.0 + 5.0 = 8.0
                                               #Posição [0, 1] do resultado: 2.0 + 4.0 = 6.0
                                               #Posição [0, 2] do resultado: 3.0 + 5.0 = 8.0
                                               #Posição [1, 0] do resultado: 6.0 + 8.0 = 14.0
                                               #Posição [1, 1] do resultado: 7.0 + 9.0 = 16.0
                                               #Posição [1, 2] do resultado: 6.0 + 8.0 = 14.0

(tensor([[[3., 2., 3.],
          [5., 4., 5.]],
 
         [[6., 7., 6.],
          [8., 9., 8.]],
 
         [[3., 2., 3.],
          [5., 4., 5.]],
 
         [[6., 7., 6.],
          [8., 9., 8.]]]),
 torch.Size([4, 2, 3]),
 tensor([[ 8.,  6.,  8.],
         [14., 16., 14.],
         [ 8.,  6.,  8.],
         [14., 16., 14.]]),
 torch.Size([4, 3]))

In [28]:
x, x.shape, x.sum(axis=1), x.sum(axis=1).shape #neste caso (tensor 4D), a dimensão 1 engloba os tensores de cada "coleção", então soma-se um elemento de
                                               #cada tensor
                                               #0+4+8, 1+5+9, 2+6+10, 3+7+11, 12+16+20....etc.

(tensor([[[3., 2., 3.],
          [5., 4., 5.]],
 
         [[6., 7., 6.],
          [8., 9., 8.]],
 
         [[3., 2., 3.],
          [5., 4., 5.]],
 
         [[6., 7., 6.],
          [8., 9., 8.]]]),
 torch.Size([4, 2, 3]),
 tensor([[ 8.,  6.,  8.],
         [14., 16., 14.],
         [ 8.,  6.,  8.],
         [14., 16., 14.]]),
 torch.Size([4, 3]))

In [29]:
A.sum(axis=[0, 1]) == A.sum()  #Somar ao longo das linhas e colunas é o mesmo que utilizar A.sum(). Retorna escalar. 
                               #Mais especificamente, se o tensor possui apenas 2 dimensões(0 e 1), e a soma for feita nas duas dimensões, 
                               #o resultado será um escalar. Caso a soma seja realizada em um numero de dimensões menor que o numero de dimensoes
                               #do tensor, então o resultado final não será escalar. Pode ser um vetor, uma matriz, ou um tensor de 3 ou mais dimensões.

tensor(True)

In [30]:
x = torch.tensor([[[3.0,2.0,3.0],[5.0,4.0,5.0]],[[6.0,7.0,6.0],[8.0,9.0,8.0]],[[3.0,2.0,3.0],[5.0,4.0,5.0]],[[6.0,7.0,6.0],[8.0,9.0,8.0]]])
x, x.shape, x.sum([0,1]), x.sum([0,1]).shape

#neste caso, o tensor é 3D e a soma é realizada em duas dimensões (0 e 1). O resultado final tem o numero de dimensões da quantidade de dimensoes que nao
#foi incorporada no somatorio. Além disso, o numero de elementos no resultado final será igual ao tamanho da dimensão que naõ entrou na soma.
#Ou seja, resultado final tem uma dimensão -> apenas uma dimensão (2) nao foi usada na soma. Resultado final tem 3 elementos -> dimensão 2 tem tamanho 3.

(tensor([[[3., 2., 3.],
          [5., 4., 5.]],
 
         [[6., 7., 6.],
          [8., 9., 8.]],
 
         [[3., 2., 3.],
          [5., 4., 5.]],
 
         [[6., 7., 6.],
          [8., 9., 8.]]]),
 torch.Size([4, 2, 3]),
 tensor([44., 44., 44.]),
 torch.Size([3]))

In [31]:
x = torch.arange(36).reshape(2, 3, 2, 3)
x, x.shape, x.sum([0,1]), x.sum([0,1]).shape

#neste caso, tensor tem 4 dimensões, e a soma foi feita ao longo de duas (0 e 1). Resultado final tem duas dimensões (tensor 2D), pois duas dimensões não 
#foram usadas na soma. ALém disso, resultado final tem 6 elementos pois uma das dimensões nao usadas tem 2 elementos e a outra tem 3 (2*3=6).

(tensor([[[[ 0,  1,  2],
           [ 3,  4,  5]],
 
          [[ 6,  7,  8],
           [ 9, 10, 11]],
 
          [[12, 13, 14],
           [15, 16, 17]]],
 
 
         [[[18, 19, 20],
           [21, 22, 23]],
 
          [[24, 25, 26],
           [27, 28, 29]],
 
          [[30, 31, 32],
           [33, 34, 35]]]]),
 torch.Size([2, 3, 2, 3]),
 tensor([[ 90,  96, 102],
         [108, 114, 120]]),
 torch.Size([2, 3]))

In [32]:
A.mean(), A.sum() / A.numel()  #calculo da media de um tensor. divide the sum by the total number of elements
                               #A.numel returns the total number of elements in the input tensor

(tensor(2.5000), tensor(2.5000))

In [33]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0] #também é possível tirar a média de uma dimensão específica. Note que a soma é feita ao longo de uma 
                                           #unica dimensão e a divisão também é feita pelo número de elementos da mesma dimensão
A, A.shape[0], A.sum(axis=0), A.mean(axis=0)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 2,
 tensor([3., 5., 7.]),
 tensor([1.5000, 2.5000, 3.5000]))

In [34]:
sum_A = A.sum(axis=1, keepdims=True) #keepdims mantém o número total de dimensões inalterado. Ou seja, A tinha 2 dimensões (0 e 1),
                                     # e após a soma, o resultado ainda possui essa configuração. Se não usar keepdims, o resultado
                                     # fica com apenas uma dimensão ([3., 12.]). Resumidamente, o tensor resultante tem a mesma forma.
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [35]:
#Since sum_A keeps its two axes after summing each row, we can divide A by sum_A with broadcasting to create a matrix 
#where each row sums up to 1
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [36]:
A.cumsum(axis=0) #esta função dá a soma cumulativa ao longo de alguma das dimensões. Neste caso, a primeira iteração do somatório
                 #inclui apenas os elementos da primeira linha, portanto, os resultados serão 0., 1., e 2.
                 #A segunda iteração já soma os valores da segunda linha aos valores calculados anteriormente: 
                 #0. + 3.= 3. | 1. + 4. = 5. | 2. + 5. = 7. 

tensor([[0., 1., 2.],
        [3., 5., 7.]])

In [37]:
x = torch.arange(3, dtype=torch.float)
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y) #torch.dot calcula o produto interno de x e y, ou seja, (0*1) + (1*1) + (2*1) = 3

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [38]:
#Alternativamente, é possível calcular o produto interno "manualmente" fazendo a multiplicação seguida por uma soma:
torch.sum(x * y)

tensor(3.)

In [39]:
A, x, A.shape, x.shape, torch.mv(A, x), A@x #torch.mv = multiplicação de matriz e vetor. @ é inteligente e serve tanto para
                                            #multiplicação matriz-vetor ou matriz-matriz

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([0., 1., 2.]),
 torch.Size([2, 3]),
 torch.Size([3]),
 tensor([ 5., 14.]),
 tensor([ 5., 14.]))

In [40]:
B = torch.ones(3, 4)
A, B, torch.mm(A, B), A@B #torch.mm = multiplicação de matrizes
#multiplica linha de A com coluna de B e soma o resultado. Depois multiplica a proxima linha de A com a mesma coluna e soma. 
#Depois repete tudo com a proxima coluna de B e assim por diante

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

In [64]:
import math
#The Euclidean norm that we all learned in elementary school geometry when calculating the 
#hypotenuse of a right triangle is the square root of the sum of squares of a vector’s elements. 
#Formally, this is called the l2 norm.
u = torch.tensor([3.0, -4.0])
torch.norm(u), math.sqrt(3.0**2 + (-4.0)**2) #torch.norm calula a norma de um tensor. Note que a resultado de math nao retorna um tensor,
                                             #até pq precisa receber números como input

(tensor(5.), 5.0)

In [65]:
#The l1 norm is also common and the associated measure is called the Manhattan distance. By definition, the 
#l1 norm sums the absolute values of a vector’s elements. Compared to the l2, it is less sensitive to outliers
#To compute the l1 norm, we compose the absolute value with the sum operation:
torch.abs(u).sum()

tensor(7.)

In [66]:
#Tanto as normas l1 quanto l2 são casos especiais da regra geral de normas lp: (SUM_i=1^n{|x_i|^p})^1/p
#note que se p=1, se torna a norma l1, e se p=2 se torna a norma l2

In [69]:
#Existe também a norma espectral e a norma de Frobenius. A de Frobenius é como se fosse uma l2 de um vetor com forma de matriz.
#É dada pela raiz quadrada do somatorio dos quadrados dos elementos de uma matriz.
torch.norm(torch.ones((4, 9))) #note que a função usada é igual a da l2 anterior, mas possui linhas e colunas.

tensor(6.)